spring.application.name: arclib
spring:
#    datasource:
#      url: jdbc:postgresql://localhost:5432/arclib
#      username: arclib
#      password: vuji61oilo
#      driver-class-name: org.postgresql.Driver
#      name: mainPool
#    jpa:
#      show-sql: false
#      database-platform: org.hibernate.dialect.PostgreSQL9Dialect
#      hibernate:
#        ddl-auto: validate
#        naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
#        use-new-id-generator-mappings: true
  datasource:
    url: jdbc:h2:mem:example-simple;MODE=Oracle;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
liquibase:
  changeLog: classpath:/dbchangelog.arclib.xml
  url: jdbc:postgresql://localhost:5432/arclib
  user: arclib
  password: vuji61oilo
camunda:
  bpm:
    application:
      isDeleteUponUndeploy: false
      isScanForProcessDefinitions: false
      isDeployChangedOnly: true
      isResumePreviousVersions: true
      resumePreviousBy: a value
    job-execution:
      enabled: true
    metrics:
      enabled: false
      db-reporter-activate: false
arclib:
  workspace: workspace
